#!/bin/bash

APP_NAME="ScreenOCR"
BUILD_PATH=".build/debug"
APP_BUNDLE="$APP_NAME.app"
CONTENTS="$APP_BUNDLE/Contents"
MACOS="$CONTENTS/MacOS"
RESOURCES="$CONTENTS/Resources"

# 1. Build
swift build

# 2. Create Bundle Structure
rm -rf "$APP_BUNDLE"
mkdir -p "$MACOS"
mkdir -p "$RESOURCES"

# 3. Copy Executable
cp "$BUILD_PATH/$APP_NAME" "$MACOS/"

# 4. Create Info.plist
cat > "$CONTENTS/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>com.example.$APP_NAME</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>LSUIElement</key>
    <true/> <!-- This hides it from Dock and makes it a Menu Bar app -->
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
</dict>
</plist>
EOF

# 5. Process App Icon
# We expect app_icon.png to exist in the current directory (generated by AI)
if [ -f "app_icon.png" ]; then
    echo "Processing App Icon..."
    ICONSET="AppIcon.iconset"
    mkdir -p "$ICONSET"
    
    # Create standard sizes with explicit png format
    sips -z 16 16     -s format png "app_icon.png" --out "$ICONSET/icon_16x16.png" > /dev/null
    sips -z 32 32     -s format png "app_icon.png" --out "$ICONSET/icon_16x16@2x.png" > /dev/null
    sips -z 32 32     -s format png "app_icon.png" --out "$ICONSET/icon_32x32.png" > /dev/null
    sips -z 64 64     -s format png "app_icon.png" --out "$ICONSET/icon_32x32@2x.png" > /dev/null
    sips -z 128 128   -s format png "app_icon.png" --out "$ICONSET/icon_128x128.png" > /dev/null
    sips -z 256 256   -s format png "app_icon.png" --out "$ICONSET/icon_128x128@2x.png" > /dev/null
    sips -z 256 256   -s format png "app_icon.png" --out "$ICONSET/icon_256x256.png" > /dev/null
    sips -z 512 512   -s format png "app_icon.png" --out "$ICONSET/icon_256x256@2x.png" > /dev/null
    sips -z 512 512   -s format png "app_icon.png" --out "$ICONSET/icon_512x512.png" > /dev/null
    sips -z 1024 1024 -s format png "app_icon.png" --out "$ICONSET/icon_512x512@2x.png" > /dev/null
    
    # Create icns
    if iconutil -c icns "$ICONSET"; then
        mv AppIcon.icns "$RESOURCES/"
        echo "Created and added AppIcon.icns"
    else
        echo "iconutil failed. Using PNG fallback."
        cp "app_icon.png" "$RESOURCES/AppIcon.png"
    fi
    
    rm -rf "$ICONSET"
    
    # Force set the icon using the Swift script as a redundancy
    echo "Forcing icon on bundle..."
    swift set_icon.swift "app_icon.png" "$APP_BUNDLE"
else
    echo "Warning: app_icon.png not found. App will have default icon."
fi

# 6. Ad-Hoc Code Sign (Important for Permissions)
codesign --force --deep --sign - "$APP_BUNDLE"

echo "Created $APP_BUNDLE"
echo "To run: open $APP_BUNDLE"
